# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='IDC地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='email',
            field=models.CharField(max_length=50, verbose_name='IDC邮箱'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='IDC名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='IDC联系电话'),
        ),
    ]
