# Generated by Django 2.1.7 on 2019-03-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='功能大类', max_length=30, verbose_name='功能大类')),
                ('name_en', models.CharField(help_text='功能大类英文', max_length=30, verbose_name='功能大类英文')),
            ],
            options={
                'verbose_name': '功能大类',
                'verbose_name_plural': '功能大类',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='所在机房', max_length=30, verbose_name='所在机房')),
                ('tree_id', models.IntegerField(verbose_name='tree_id')),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='Subfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='功能小类', max_length=30, verbose_name='功能小类')),
                ('name_en', models.CharField(help_text='功能小类英文', max_length=30, verbose_name='功能小类英文')),
                ('function', models.ForeignKey(help_text='所在功能大类', on_delete=django.db.models.deletion.CASCADE, related_name='sub_function', to='kiwi.Function', verbose_name='所在功能大类')),
            ],
            options={
                'verbose_name': '功能小类',
                'verbose_name_plural': '功能小类',
            },
        ),
        migrations.AddField(
            model_name='function',
            name='idc',
            field=models.ForeignKey(help_text='所在IDC', on_delete=django.db.models.deletion.CASCADE, related_name='fun_idc', to='kiwi.Idc', verbose_name='所在IDC'),
        ),
    ]
