# Generated by Django 2.1.7 on 2019-03-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='idc',
            field=models.ForeignKey(help_text='所在IDC', on_delete=django.db.models.deletion.CASCADE, related_name='idc_fun', to='kiwi.Idc', verbose_name='所在IDC'),
        ),
        migrations.AlterField(
            model_name='subfunction',
            name='function',
            field=models.ForeignKey(help_text='所在功能大类', on_delete=django.db.models.deletion.CASCADE, related_name='fun_sub', to='kiwi.Function', verbose_name='所在功能大类'),
        ),
    ]
