# Generated by Django 2.1.7 on 2019-03-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0003_az'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='idc',
        ),
        migrations.AddField(
            model_name='function',
            name='az',
            field=models.ForeignKey(default='', help_text='所在AZ', on_delete=django.db.models.deletion.CASCADE, related_name='az_fun', to='kiwi.AZ', verbose_name='所在AZ'),
        ),
        migrations.AlterField(
            model_name='az',
            name='name',
            field=models.CharField(help_text='AZ', max_length=20, verbose_name='AZ'),
        ),
    ]
