# Generated by Django 2.1.7 on 2019-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0005_auto_20190316_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='az',
            options={'ordering': ['id'], 'verbose_name': 'AZ管理', 'verbose_name_plural': 'AZ管理'},
        ),
        migrations.AlterField(
            model_name='function',
            name='name_en',
            field=models.CharField(help_text='功能大类英文', max_length=30, null=True, verbose_name='功能大类英文'),
        ),
        migrations.AlterField(
            model_name='subfunction',
            name='name_en',
            field=models.CharField(help_text='功能小类英文', max_length=30, null=True, verbose_name='功能小类英文'),
        ),
    ]
