# Generated by Django 2.0.9 on 2018-10-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='厂商名称')),
                ('tel', models.CharField(max_length=15, null=True, verbose_name='联系电话')),
                ('mail', models.CharField(max_length=32, null=True, verbose_name='联系邮件')),
                ('remark', models.CharField(max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'resourse_manufacture',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='型号名称')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.Manufacturer', verbose_name='所属制造商')),
            ],
            options={
                'db_table': 'resource_productmodel',
                'ordering': ['id'],
            },
        ),
    ]
