# Generated by Django 2.0.9 on 2018-10-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20181013_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', 'can view server'),)},
        ),
    ]
