# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-02 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20181014_0321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ip',
            table='resource_ip',
        ),
    ]
