# Generated by Django 2.1.7 on 2019-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, '申请'), (2, '已审核'), (3, '灰度'), (4, '上线'), (5, '取消上线')], default=0, verbose_name='上线状态'),
        ),
    ]
