# Generated by Django 2.0.9 on 2018-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('address', models.CharField(max_length=200, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=15, verbose_name='机房联系电话')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='机房联系email')),
                ('letter', models.CharField(max_length=5, verbose_name='idc 字母简称')),
            ],
            options={
                'db_table': 'resource_idc',
            },
        ),
    ]
